FROM php:8.2-fpm-alpine

COPY docker/php/ini/php.ini /usr/local/etc/php/
# Install php extensions
RUN apk update; \
    apk add \
        --no-cache \
            imagemagick-libs \
            php8-imagick \
            gd \
            util-linux \
            zip \
            unzip \
            php8-intl \
            php8-zip \
            php8-iconv \
            php8-opcache \
            php8-mysql\
            php8-mysqli \
            php8-pdo_mysql; \
    apk add \
        --no-cache \
        --virtual build-dependencies \
            freetype-dev \
            libjpeg-turbo-dev \
            libpng-dev \
            zlib-dev \
            icu-dev \
            libzip-dev \
            tzdata; \
    apk add \
        --no-cache \
        --virtual dev-dependencies \
            bash \
            git \
            sqlite

RUN cp /usr/share/zoneinfo/${TIMEZONE} /etc/localtime; \
    echo ${TIMEZONE} > /etc/timezone

RUN docker-php-ext-configure zip --with-libzip; \
    docker-php-ext-configure intl; \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/; \
    docker-php-ext-install \
        -j$(getconf _NPROCESSORS_ONLN) \
          gd \
          zip \
          intl \
          iconv \
          mysqli \
          mysql \
          opcache \
          pdo_mysql; \
    docker-php-ext-enable \
              gd \
              zip \
              intl \
              iconv \
              mysqli \
              mysql \
              opcache \
              pdo_mysql; \
    apk del build-dependencies
