---
version: '3.4'
services:
  www:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/www/DockerFile
    volumes:
      - ./src:/var/www/html
      - ./docker/www/etc/conf.d:/etc/nginx/conf.d:rw,Z
    ports:
      - '8080:80'
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/php/DockerFile
    volumes:
      - ./src:/var/www/html
    expose:
      - '9000'
  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/db/DockerFile
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "secret"
